name: Test Action

on:
  - pull_request_target

jobs:
  run:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.TEST_ACTION_GITHUB_TOKEN }}
          package-block-list: '@actions/core, @actions/github'
