name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: npm install, build and test
        run: |
          npm ci
          npm run lint
          npm run build
          npm test
        env:
          CI: true
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./src/coverage/clover.xml
